# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  convforn-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: convforn-mysql
    volumes:
      - convforn-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=convforn
      - MYSQL_DATABASE=convforn
      - MYSQL_USER=convforn
      - MYSQL_PASSWORD=convforn

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: convforn-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql